blank_issues_enabled: false
contact_links:
  - name: 👪 Prismic Community Forum
    url: https://community.prismic.io
    about: Ask a question about Prismic itself, such as the Asset API's behavior. This package is not maintained by Prismic, report issues with it here instead.
